CREATE TABLE IF NOT EXISTS jobs (
    title TEXT,
    normalized_title TEXT,
    company_name TEXT,
    ats_name TEXT,
    industry TEXT,
    function TEXT,
    occupational_category TEXT,
    employment_type TEXT,
    work_model TEXT,
    schedule TEXT,
    shift TEXT,
    experience_level TEXT,
    job_level_normalized TEXT,
    years_experience_numeric DOUBLE PRECISION,
    education_level TEXT,
    skills_required TEXT,
    minimum_qualifications TEXT,
    preferred_qualifications TEXT,
    responsibilities TEXT,
    certifications TEXT,
    languages_required TEXT,

    salary_min DOUBLE PRECISION,
    salary_max DOUBLE PRECISION,
    salary_currency TEXT,
    salary_rate_unit TEXT,
    salary_type TEXT,
    pay_frequency TEXT,
    bonus TEXT,
    equity TEXT,
    on_target_earnings TEXT,

    benefits TEXT,
    city TEXT,
    country TEXT,
    location_resolved TEXT,
    locations TEXT,
    remote_eligibility_regions TEXT,

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    visa_sponsorship_available BOOLEAN,
    work_authorization_requirements TEXT,
    security_clearance BOOLEAN,
    relocation_assistance BOOLEAN,
    travel_required BOOLEAN,
    travel_percentage DOUBLE PRECISION,

    date_posted TIMESTAMP,
    closing_date TIMESTAMP,
    job_description TEXT,

    job_posted_year DOUBLE PRECISION,
    job_posted_month DOUBLE PRECISION,
    job_posted_month_name TEXT,
    job_posted_day DOUBLE PRECISION,
    job_posted_weekday TEXT,
    job_posted_quarter DOUBLE PRECISION,

    salary_mid DOUBLE PRECISION,

    has_salary BOOLEAN,
    is_remote BOOLEAN,
    is_hybrid BOOLEAN,
    is_onsite BOOLEAN,
    has_experience_requirement BOOLEAN
);